### ISSUE TITLE
DomainInfo form action - Prompt user to complete elements

### ISSUE THREAD

**Issue by gkirtzou** [MiltosD/isd_catalogue2#29]
In DomainInfo admin form, when the user selects as domain='Other', then

1. Conformance field should contain no value (i.e. Eurovoc)
2. User should be prompt to complete conformance field and domainOther field
(i.e. obligatory by condition)

**Comment by MiltosD** [comment]
Resolved daa4a464df161d83e31b17e64034049e77738439
